on:
  workflow_call:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        # Test the last two golang major versions
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - 
      name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - 
      name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - 
      name: Check code
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
    -
      name: Run Tests
      run: go test -cover -p 1 -race -v ./...